default:
  image: node:14
  before_script:
    - apt update
    - yarn install

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn test:unit

deploy:
  stage: deploy
  script:
    - apt -y install rpm
    - yarn electron:build
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.snap
      - dist_electron/*.deb
      - dist_electron/*.rpm
